//CREATE PRODUCT
export const NEW_PRODUCT_REQUEST = 'NEW_PRODUCT_REQUEST'
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS'
export const NEW_PRODUCT_RESET = 'NEW_PRODUCT_RESET'
export const NEW_PRODUCT_FAIL = 'NEW_PRODUCT_FAIL'
//ALL PRODUCT
export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCES'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'

//SINGLE PRODUCT
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const ADMIN_PRODUCTS_REQUEST = 'ADMIN_PRODUCTS_REQUEST'
export const ADMIN_PRODUCTS_SUCCESS = 'ADMIN_PRODUCTS_SUCCESS'
export const ADMIN_PRODUCTS_FAIL = 'ADMIN_PRODUCTS_FAIL'
export const ADMIN_PRODUCTS_RESET = 'ADMIN_PRODUCTS_RESET'

//UPDATE PRODUCT
export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET'

//DELETE PRODUCT
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'

//soft delete
export const SOFTDELETE_PRODUCT_REQUEST = 'SOFTDELETE_PRODUCT_REQUEST'
export const SOFTDELETE_PRODUCT_SUCCESS = 'SOFTDELETE_PRODUCT_SUCCESS'
export const SOFTDELETE_PRODUCT_RESET = 'SOFTDELETE_PRODUCT_RESET'
export const SOFTDELETE_PRODUCT_FAIL = 'SOFTDELETE_PRODUCT_FAIL'

export const RESTORE_PRODUCT_REQUEST = 'RESTORE_PRODUCT_REQUEST'
export const RESTORE_PRODUCT_SUCCESS = 'RESTORE_PRODUCT_SUCCESS'
export const RESTORE_PRODUCT_RESET = 'RESTORE_PRODUCT_RESET'
export const RESTORE_PRODUCT_FAIL = 'RESTORE_PRODUCT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'